development:
  BASE_URI: "localhost"
  REDISTOGO_URL: "redis://localhost/7"
  ARTIST: "Jonathan Coulton"
  NUMBER: 42
  BASE: 3

test:
  BASE_URI: "localhost"
  REDISTOGO_URL: "redis://localhost/9"
  ARTIST: "Jonathan Coulton"
  NUMBER: 42
  BASE: 3

