development:
  BASE_URI: "localhost"
  REDISTOGO_URL: "redis://localhost/7"
  DATABASE_URL: "postgres://localhost/aji_dev"

test:
  BASE_URI: "localhost"
  REDISTOGO_URL: "redis://localhost/9"
  DATABASE_URL: "postgres://localhost/aji_test"

